"""empty message

Revision ID: c857df5a7dd5
Revises: 
Create Date: 2018-11-26 23:17:45.586595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c857df5a7dd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('ifsc', sa.String(length=25), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ifsc')
    )
    op.create_index(op.f('ix_bank_bank_id'), 'bank', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_bank_id'), table_name='bank')
    op.drop_table('bank')
    # ### end Alembic commands ###
